### ISSUE TITLE
Typos and Missing keywords

### ISSUE THREAD

**Issue by mpvano** [jarjuk/UTG900#3]
There seem to be a huge number of typos in here - too many too list individually, but none of the commands appear to work without significant editing.

hope you have another revision that actually works - I've had to do a lot of editing to get it to work, and everything new I try seems to have things missing - e.g. The sine (and many other) command arguments in the dictionary are wrong due to the definition having an embedded expression setting them to be equal to ANOTHER command keyword!

The sine command dictionary entry has no entry for channel (I'm not sure anything else does, either).

The phase argument doesn't seem to work since no units are passed to the parser.

thanks,

Mario Vano

**Comment by jarjuk** [comment]
Hello,

I am sorry for the typos!

This version has not been updated.   This "exercise" uses UI to access and control the device. Drawbacks in the implementation:
 
- I could not read device mode (channel on/off) from the UI. Hence, the tool keeps internal state for the channels (not too robust solution, I am afraid)
- Possible changes user interface on later versions may easily break the communication protocol, and, as the result, tool may or may not work on new versions.

READ has notice _"Superseded by `ebUnit` -command in https://github.com/jarjuk/ebench"_. This version may work better.  However, I have not put any effort on maintaining that version either, because of the fundamental problems above.

It seems that the communication protocol has been "hacked", and I propose using API for communication/control this device. 

https://www.eevblog.com/forum/testgear/uni-t-utg932utg962-200msas-function-arbitrary-waveform-generator-220394/msg3561559/#msg3561559

PS.
A warning regarding https://github.com/jarjuk/ebench": It misses a vital feature to be able to do round-trip configuration (=read current configuration from the device and write this configuration back).  Sigrok may be one solution, but to my understanding sigrok understand only a subset of device features. 

I am closing this issue

**Comment by mpvano** [comment]
Thanks (and thanks for the work you did on it - it's a good beginning).

M
